repos:
  - repo: local
    hooks:
      - id: check
        name: format
        entry: hatch fmt --check
        language: system
        types: [python]
        verbose: true
      - id: type-check
        name: type-check
        entry: hatch run mypy src/app_store_web_scraper/*.py tests/*.py
        language: system
        types: [python]
        verbose: true
      - id: test
        name: test
        entry: hatch test
        language: system
        types: [python]
        verbose: true
        pass_filenames: false