name: Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Build package
      run: hatch build

    - name: Publish package
      run: hatch publish
